name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-22"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTRjN2JkODAtYjk0Mi00ZmRlLWJhZTktNjE2OTlhNjRmMmU4IiwidGVuYW50X2lkIjoiOGRkMjQwN2EzNGFiN2I3NDI1MDFiYzcxYzI0NDNjOTg2M2NmYzllZGFjMGY5YWVjMTU5MGI0ODNjYmE2NDJlNyIsImludGVybmFsX3NlY3JldCI6ImE4ZTgyNjI0LWU4ZDktNDZlYS1hNGE4LWM5OGFkMGVkZjQ5ZSJ9.rU-lMdi97u3qPetQJmJMTGqOxkQ8sJrkPlznL-iiOHY"
JWT_SECRET = "adityakumar"
